// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/book-appointment": {
    params: {};
  };
  "/book-cleaning": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/book-appointment" | "/book-cleaning" | "/contact";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/book-appointment.tsx": {
    id: "routes/book-appointment";
    page: "/book-appointment";
  };
  "routes/book-cleaning.tsx": {
    id: "routes/book-cleaning";
    page: "/book-cleaning";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/index": typeof import("./src/routes/index.tsx");
  "routes/about": typeof import("./src/routes/about.tsx");
  "routes/book-appointment": typeof import("./src/routes/book-appointment.tsx");
  "routes/book-cleaning": typeof import("./src/routes/book-cleaning.tsx");
  "routes/contact": typeof import("./src/routes/contact.tsx");
};